POST http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstName": "Sergio",
    "lastName": "Giron",
    "email": "isadmin@hola.com",
    "age": 30,
    "password": "hellowor",
    "isAdmin": true
}
###

POST  http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json

{
    "email": "whatever@hola.com",
    "password": "hellowor"
}
###
POST http://localhost:3000/api/v1/garmets HTTP/1.1
content-type: application/json
Authorization: 
{
   "name": "T-shirt summer",
   "description": "Nice t-shirt with a print",
   "category": "T-shirt",
   "stock": 2,
  "variant": {
    "price": 10,
    "color": "white",
    "size": "M"
  },
  "image": "http:something",
  "totalRating": 5,
  "reviews": [{ "name": "hola", "comment": "good", "rating": 5 }]
}






###

GET http://localhost:3000/api/v1/users/60c372cfc6aeef34ff246ed1 HTTP/1.1
content-type: application/json


###

DELETE http://localhost:3000/api/v1/garmets/60a52618a2e17367699063de HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/v1/users/60c88fd1b17efa6026c2be3f HTTP/1.1
content-type: application/json

{
    "firstName": "Sonia",
    "lastName": "Giron",
    "email": "whatever@hola.com",
    "age": 40,
    "password": "hellowor",
    "isAdmin": true
}