POST http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstName": "Javier",
    "lastName": "Giron",
    "email": "adions@hola.com",
    "age": 39,
    "password": "hellowor",
    "isAdmin": false
}
###
POST http://localhost:3000/api/v1/localhost:3000/api/v1/garmets HTTP/1.1
content-type: application/json

{
   "title": "T-shirt summer",
   "description": "Nice t-shirt with a print",
   "category": "T-shirt",
   "countInStock": 2,
  "variant": {
    "price": 10,
    "color": "white",
    "size": "M",
  },
  "image": "http:something",
  "generalRating": 5,
  "reviews": "ReviewDocument[]"
}





###

GET http://localhost:3000/api/v1/garmets HTTP/1.1
content-type: application/application/json


###

DELETE http://localhost:3000/api/v1/garmets/60a52618a2e17367699063de HTTP/1.1
content-type: application/application/json

###

PUT http://localhost:3000/api/v1/garmets/id HTTP/1.1
content-type: application/application/json