POST http://localhost:3000/api/v1/garmets HTTP/1.1
content-type: application/json

{
    "name": "Cotton T-shirt",
    "genres": "Male",
    "category": "T-Shirt",
    "brand": "Diesel",
    "size": "M",
    "season": "Summer",
    "garmetRef": 1
}

###

GET http://localhost:3000/api/v1/garmets HTTP/1.1
content-type: application/application/json


###

DELETE http://localhost:3000/api/v1/garmets/60a52618a2e17367699063de HTTP/1.1
content-type: application/application/json

###

PUT http://localhost:3000/api/v1/garmets/id HTTP/1.1
content-type: application/application/json